contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_create, name='contact_create'),
    path('<int:pk>/', views.contact_detail, name='contact_detail'),
    path('<int:pk>/update/', views.contact_update, name='contact_update'),
    path('<int:pk>/delete/', views.contact_delete, name='contact_delete'),
]

donation/urls.py
from django.urls import path
from . import views


app_name='donation'
urlpatterns = [
    path('', views.donation_form, name='donation_form'),
    path('charge/', views.charge, name='charge'),
]

myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('registration/', include('registration.urls')),
    path('projects/', include('projects.urls')),
    path('contact/', include('contact.urls')),
    path('donation/', include('donation.urls')),
    path('accounts/', include(urls)),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns =[
    path('', views.home, name='home' ),
    path('about_me/', views.about_me, name='about_me'),
]

projects/urls.py
from django.urls import path
from . import views
app_name = 'projects'
urlpatterns = [
    path('projects/', views.project_list, name='project_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/create/', views.project_create, name='project_create'),  
    path('projects/<int:project_id>/update/', views.project_update, name='project_update'),
    path('projects/<int:project_id>/delete/', views.project_delete, name='project_delete'),
]

registration/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .import views

app_name = 'registration'
urlpatterns = [
    path('register', views.register, name='register'),   
    path('login', views.user_login, name='login'),  
    path('logout', views.user_logout, name='logout'),   
    # ... autres URL ...
    path('reset_password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # ... autres URL ...

]

portfolio/models.py
from django.contrib.auth.models import User
from django.db import models

class Skill(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

class Education(models.Model):
    institution = models.CharField(max_length=100)
    degree = models.CharField(max_length=50)
    field_of_study = models.CharField(max_length=50)
    graduation_year = models.IntegerField()

    def __str__(self):
        return f"{self.degree} in {self.field_of_study} at {self.institution}, {self.graduation_year}"

class Experience(models.Model):
    job_title = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return f"{self.job_title} at {self.company}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    bio = models.TextField()
    skills = models.ManyToManyField(Skill)
    education = models.ManyToManyField(Education)
    experience = models.ManyToManyField(Experience)

    # Ajoutez les champs supplémentaires dont vous avez besoin
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    github_url = models.URLField(blank=True, null=True)
    facebook_url = models.URLField(blank=True, null=True)
    github_url = models.URLField(blank=True, null=True)
    linkedin_url = models.URLField(blank=True, null=True)
    twitter_handle = models.CharField(max_length=50, blank=True, null=True)
    photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}'s Profile"

portfolio/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from .models import Profile

def home(request):
    return render(request, 'portfolio/home.html')

def about_me(request):
    profile = Profile.objects.first()
    return render(request, 'portfolio/about_me.html', {'profile': profile})

portfolio/templates/portfolio/about_me.html
{% extends 'portfolio/base.html' %}

{% block title %}About Me{% endblock %}

{% block content %}
  <div class="container animated">
    <h2 class="mt-4 mb-4 text-center">About Me</h2>

    <div class="row">
      <div class="col-md-4">
        <img src="{{ profile.photo.url }}" alt="{{ profile.first_name }} {{ profile.last_name }}" class="img-fluid rounded-circle">
      </div>

      <div class="col-md-8">
        <p class="lead"><strong>Name:</strong> {{ profile.first_name }} {{ profile.last_name }}</p>
        <p><strong>Bio:</strong> {{ profile.bio }}</p>
        <p><strong>Email:</strong> {{ profile.email }}</p>
        <p><strong>Phone Number:</strong> {{ profile.phone_number }}</p>
        <p><strong>Website:</strong> <a href="{{ profile.website }}" target="_blank">{{ profile.website }}</a></p>
        <p><strong>Github URL:</strong> <a href="{{ profile.github_url }}" target="_blank">{{ profile.github_url }}</a></p>
        <p><strong>Facebook URL:</strong> <a href="{{ profile.facebook_url }}" target="_blank">{{ profile.facebook_url }}</a></p>
        <p><strong>LinkedIn URL:</strong> <a href="{{ profile.linkedin_url }}" target="_blank">{{ profile.linkedin_url }}</a></p>
        <p><strong>Twitter Handle:</strong> {{ profile.twitter_handle }}</p>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-md-6">
        <h3>Skills:</h3>
        <ul class="list-group">
          {% for skill in profile.skills.all %}
            <li class="list-group-item">{{ skill.name }} - {{ skill.description }}</li>
          {% endfor %}
        </ul>
      </div>

      <div class="col-md-6">
        <h3>Education:</h3>
        <ul class="list-group">
          {% for education in profile.education.all %}
            <li class="list-group-item">{{ education.degree }} in {{ education.field_of_study }} at {{ education.institution }}, {{ education.graduation_year }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-md-12">
        <h3>Experience:</h3>
        <ul class="list-group">
          {% for experience in profile.experience.all %}
            <li class="list-group-item">
              <strong>{{ experience.job_title }} at {{ experience.company }}</strong>,
              {{ experience.start_date }} - {{ experience.end_date|default:"Present" }}
              <p>{{ experience.description }}</p>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">

    <title>{% block title %}My Portfolio{% endblock %}</title>
</head>

<body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow p-3 mb-5 bg-body-tertiary rounded">
        <a class="navbar-brand" href="/"><img class="logo" src="{% static 'images/myLogo1.png' %}"
                alt="My Portfolio"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:about_me' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'projects:project_list' %}">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact_create' %}">Contact</a>
                    <a class="nav-link" href="{% url 'donation:donation_form' %}">Donate</a>
                </li>
                {% if user.is_authenticated %}
                <!-- Add logout link if the user is authenticated -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:logout' %}">Logout</a>
                </li>
                {% else %}
                <!-- Add registration and login links if the user is not authenticated -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:register' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- End Navigation Bar -->

    <!-- Main Content -->
    <div class="container-fluid mt-4">
        {% block content %}{% endblock %}
    </div>
    <!-- End Main Content -->

    <!-- Footer -->
    <footer class="bg-light text-center rounded">
        <div class="container p-4">
            <!-- Social Media Icons -->
            <section class="mb-4">
                <a class="btn btn-outline-dark btn-floating m-1"
                    href="https://www.facebook.com/profile.php?id=100071095987734&sk=about" role="button"><i
                        class="fab fa-facebook-f"></i></a>
                <a class="btn btn-outline-dark btn-floating m-1" href="https://twitter.com/OmeusMarc" role="button"><i
                        class="fab fa-twitter"></i></a>
                <a class="btn btn-outline-dark btn-floating m-1"
                    href="https://www.linkedin.com/in/marc-donald-omeus-3a10b5219/" role="button"><i
                        class="fab fa-linkedin"></i></a>


                <a class="btn btn-outline-dark btn-floating m-1" href="https://www.instagram.com/omarcdonald/"
                    role="button"><i class="fab fa-instagram"></i></a>
            </section>
            <!-- End Social Media Icons -->

            <!-- Contact -->
            <section class="mb-4">
                <p>
                    <a class="nav-link" href="{% url 'contact:contact_create' %}">Contact me</a>
                </p>
            </section>
            <!-- End Contact -->

            <!-- Copyright -->
            <div class="text-center p-3">
                © 2024 My Portfolio. All rights reserved.
            </div>
            <!-- End Copyright -->
        </div>
    </footer>
    <!-- End Footer -->

    <!-- Bootstrap JS, Popper.js, jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block title %}Welcome to Marc-Donald Omeus's Portfolio{% endblock %}

{% block content %}
<div class="jumbotron text-center">
  <h1 class="display-3">Welcome to My Portfolio</h1>
  <h3 class="display-4">I'm Marc-Donald Omeus</h3>
  <p class="lead">Explore my skills, projects, and more.</p>
  <hr class="my-4">
  <h5>Check out the different sections to learn more about me.</h5>
  <a class="btn btn-primary btn-lg mb-4" href="{% url 'portfolio:about_me' %}" role="button">About Me</a>

  <div class="mb-4">
    <a class="btn btn-success btn-lg" href="{% url 'projects:project_list' %}" role="button">My Projects</a>
    <a class="btn btn-info btn-lg" href="/static/resume/my_resume.pdf" role="button" target="_blank">Download Resume</a>
  </div>

  <!-- Add a section for Testimonials -->
  <div class="container mt-5">
    <h2>What Others Say</h2>
    <div id="carouselTestimonials" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <p class="lead">"Marc-Donald is an exceptional talent, his dedication to his work is inspiring." - Gertrude OMEUS, CEO</p>
        </div>
        <div class="carousel-item">
          <p class="lead">"Working with Marc-Donald was a pleasure, his expertise added immense value to our project." - Livenson NICOLAS, Project Manager</p>
        </div>
        <!-- Add more testimonials as needed -->
      </div>
      <a class="carousel-control-prev" href="#carouselTestimonials" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselTestimonials" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

</div>

{% endblock %}